/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Additional conditions": {                       "en": "Additional conditions",                           "de": "Zusätzliche Bedingungen"},
    "Always": {                                      "en": "Always",                                          "de": "Immer"},
    "Astro times 'night' and 'nightEnd'": {          "en": "Astro times 'night' and 'nightEnd'",              "de": "Astro-Zeiten 'night' und 'nightEnd'"},
    "Cancel": {                                      "en": "Cancel",                                          "de": "Abbrechen"},
    "Deactivate to define detailed criteria for execution": {"en": "Deactivate to define detailed criteria for execution", "de": "Deaktivieren, um detaillierte Kriterien zur Ausführung zu definieren"},
    "Device Name": {                                 "en": "Device Name",                                     "de": "Geräte-Name"},
    "Do not verify": {                               "en": "Do not verify",                                   "de": "Prüfung deakiv."},
    "End": {                                         "en": "End",                                             "de": "Ende"},
    "Execute always": {                              "en": "Execute always",                                  "de": "Immer ausführen"},
    "Execution": {                                   "en": "Execution",                                       "de": "Ausführung"},
    "Execution settings for zone": {                 "en": "Execution settings for zone",                     "de": "Ausführungseinstellungen für Zone"},
    "Fri": {                                         "en": "Fri",                                             "de": "Fr"},
    "Further Adapter Options": {                     "en": "Further Adapter Options",                         "de": "Weitere Adapter-Optionen"},
    "Further Options": {                             "en": "Further Options",                                 "de": "Weitere Optionen"},
    "Hello World": {                                 "en": "Hello World",                                     "de": "Hallo Welt"},
    "Incorrect configuration": {                     "en": "Incorrect configuration",                         "de": "Fehlerhafte Konfiguration"},
    "Mo": {                                          "en": "Mo",                                              "de": "Mo"},
    "Motion sensors": {                              "en": "Motion sensors",                                  "de": "Bewegungsmelder"},
    "Name of condition": {                           "en": "Name of condition",                               "de": "Name der Bedingung"},
    "Name of motion sensor": {                       "en": "Name of motion sensor",                           "de": "Name für Bewegungsmelder"},
    "Name of trigger": {                             "en": "Name of trigger",                                 "de": "Name des Auslösers"},
    "Name of zone": {                                "en": "Name of zone",                                    "de": "Name der Zone"},
    "Never if...": {                                 "en": "Never if...",                                     "de": "Nie auslösen wenn..."},
    "Never switch if...": {                          "en": "Never switch if...",                              "de": "Nie schalten wenn..."},
    "Off after x sec": {                             "en": "Off after x sec",                                 "de": "Aus nach x sek"},
    "Ok": {                                          "en": "Ok",                                              "de": "OK"},
    "Other triggers": {                              "en": "Other triggers",                                  "de": "Andere Auslöser"},
    "Sat": {                                         "en": "Sat",                                             "de": "Sa"},
    "Sec": {                                         "en": "Sec",                                             "de": "Sek"},
    "Second(s)": {                                   "en": "Second(s)",                                       "de": "Sekunde(n)"},
    "Select": {                                      "en": "Select",                                          "de": "Auswählen"},
    "Start": {                                       "en": "Start",                                           "de": "Start"},
    "State": {                                       "en": "State",                                           "de": "Datenpunkt"},
    "State of brightness": {                         "en": "State of brightness",                             "de": "Datenpunkt Helligkeit"},
    "State of condition": {                          "en": "State of condition",                              "de": "Datenpunkt der Bedingung"},
    "State of motion sensor": {                      "en": "State of motion sensor",                          "de": "Datenpunkt Bewegungsmelder"},
    "State to switch device off": {                  "en": "State to switch device off",                      "de": "Datenpunkt zum ausschalten"},
    "State to switch device on": {                   "en": "State to switch device on",                       "de": "Datenpunkt zum einschalten"},
    "State value": {                                 "en": "State value",                                     "de": "DP-Wert"},
    "Sun": {                                         "en": "Sun",                                             "de": "So"},
    "Target devices": {                              "en": "Target devices",                                  "de": "Zielgeräte"},
    "Target off": {                                  "en": "Target off",                                      "de": "Ziel aus"},
    "Threshold": {                                   "en": "Threshold",                                       "de": "Grenze"},
    "Thu": {                                         "en": "Thu",                                             "de": "Do"},
    "Time": {                                        "en": "Time",                                            "de": "Zeit"},
    "Time based triggers": {                         "en": "Time based triggers",                             "de": "Zeitabhängige Auslöser"},
    "Time schedule and astro": {                     "en": "Time schedule and astro",                         "de": "Zeitplan und Astro"},
    "Toggle": {                                      "en": "Toggle",                                          "de": "Toggle"},
    "Trigger": {                                     "en": "Trigger",                                         "de": "Auslöser"},
    "Triggers": {                                    "en": "Triggers",                                        "de": "Auslöser"},
    "Tue": {                                         "en": "Tue",                                             "de": "Di"},
    "Value for 'off'": {                             "en": "Value for 'off'",                                 "de": "Wert für 'aus'"},
    "Value for 'on'": {                              "en": "Value for 'on'",                                  "de": "Wert für 'an'"},
    "Wed": {                                         "en": "Wed",                                             "de": "Mi"},
    "Zones": {                                       "en": "Zones",                                           "de": "Zonen"},
    "dialog.selectSettings.explanation": {           "en": "With a double click or F2  you can overwrite <strong>Value for 'on'</strong> of \"1. TARGET DEVICES\".", "de": "Durch Doppelklick oder F2 kann der <strong>Wert für 'an'</strong> von \"1. ZIELGERÄTE\" jew. überschrieben werden."},
    "log.verifyOptions.header": {                    "en": "Your configuration is faulty, please fix as follows:", "de": "Deine Konfiguration ist fehlerhaft, bitte wie folgt beheben:"},
    "log.verifyOptions.info": {                      "en": "Please note that we only checks here whether at least one active table row exists and if at least one active execution is defined in Zones. Further verifications will take place after saving of these options, which will restart the adapter. Therefore please make sure to check the ioBroker log: any additional errors will be shown there.", "de": "Bitte beachte, dass hier nur geprüft wurde, ob jeweils mindestens eine aktive Tabellenzeile vorhanden ist und ob mindestens eine aktive Ausführung in den Zonen definiert ist. Weitere Prüfungen finden nach dem Speichern beim Neustart des Adapters statt. Bitte daher auch unbedingt ins ioBroker-Log sehen. Etwaige weitere Fehler werden dort ausgegeben."},
    "tabMain.Doc": {                                 "en": "Instructions for this adapter:",                  "de": "Anleitung zu diesem Adapter:"},
    "tabMain.Welcome": {                             "en": "Welcome to the Smart Control Adapter. Current ioBroker Forum thread", "de": "Willkommen beim Smart-Control-Adapter. Aktueller ioBroker-Forum-Artikel"},
    "tabOptions.nightEndInfo": {                     "en": "Depending on the geographical coordinates set in the ioBroker admin options, there is sometimes no <code>night</code> and/or <code>nightEnd</code> available, e.g. in the summer in some German regions. If you activate this option, then the adapter will set: night = '00:00', and nightEnd = '02:00'.", "de": "Je nach den geographischen Koordinaten, die in den ioBroker-Admin-Optionen gesetzt sind, gibt es z.B. in Deutschland im Sommer teils kein <code>night</code> und <code>nightEnd</code>. Wenn du diese Option aktivierst, dann wird in diesem Fall als night = '00:00' gesetzt, und als nightEnd = '02:00'."},
    "tabOptions.nightEndOpt": {                      "en": "Set 0:00/2:00, if night/nightEnd is not available", "de": "Setze 0:00/2:00, falls kein night/nightEnd verfügbar"},
    "tabOptions.notVerifyBriHeader": {               "en": "Do not verify brightness if zone is on",          "de": "Helligkeit (Bri) nicht prüfen falls Zone an"},
    "tabOptions.notVerifyBriInfo": {                 "en": "For motion sensors and associated brightness states, you can define here if the brightness should be ignored if an associated zone is already on.<br>Use Case: 'Threshold' is the upper threshold value of the brightness, above which the adapter will not switch on anymore when the motion sensor is triggered. But this is not practical if the motion sensor e.g. switches on lights, because then no recurring motions will be detected if light is on and 'Bri' is most likely above the threshold. <br>With activation of this option, the brightness is not checked if a associated zone is already on.", "de": "Für Bewegungssensoren und zugehörige Helligkeits-Datenpunkte kannst du hier definieren, ob die Helligkeit ignoriert werden soll, falls eine zugehörige Zone bereits an ist.<br>Use Case (Anwendungsfall): 'Grenze' ist der oberere Schwellwert der Helligkeit, über dem nicht mehr eingeschaltet wird wenn der Bewegungsmelder auslöst. Dies ist jedoch nicht praxisnah, wenn der Bewegungsmelder z.B. Lichter schaltet, denn dann werden keine wiederkehrenden Bewegungen mehr erkannt, falls Licht an und 'Bri' höchstwahrscheinlich damit überhalb des Schwellwertes ist. <br>Mit Aktivierung dieser Option wird die Helligkeit nicht überprüft, falls eine zugehörige Zone bereits an ist."},
    "tabOptions.triggerAckHeader": {                 "en": "Trigger states under user states like javascript.x, 0_userdata.0, Messwerte.0, alias.x", "de": "Auslöser-Datenpunkte unterhalb von User-Datenpunkten wie javascript.x, 0_userdata.0, Messwerte.0, alias.x"},
    "tabOptions.triggerAckInfo": {                   "en": "Changes of states under adapter instances are only triggered if acknowledge (ack) = <code>true</code> (i.e. states are acknowledged/confirmed). <br>For <strong>user-own states</strong> under javascript.x, 0_userdata.0, Messwerte.0, alias.0 etc. you can change this behavior. <br><strong>Please note: </strong> If \"Any (ack:true or ack:false)\" is selected, it might be switched twice if ack:false and shortly after ack:true is set. However, this adapter prevents this with the option <i>Ignore trigger if last triggering of the same trigger was less than x seconds ago</i>.", "de": "Änderungen von Datenpunkten, die unterhalb von Adapter-Instanzen sind, werden nur getriggert, wenn acknowledge (ack) = <code>true</code> (also States gültig/bestätigt sind). <br>Für <strong>user-eigene Datenpunkte</strong> unterhalb javascript.x, 0_userdata.0, Messwerte.0, alias.0 usw. kann man das hier ändern. <br><strong>Bitte beachten: </strong> Falls \"Egal (ack:true oder ack:false)\" ausgewählt wird, wird ggf. doppelt geschaltet, wenn ack:false und kurz darauf ack:true gesetzt wird. Dieser Adapter verhindert das aber mit der Option <i>Auslöser ignorieren, falls letzes Auslösen desselben Auslösers vor weniger als x Sekunden war</i>."},
    "tabOptions.triggerAckOptAny": {                 "en": "Any (ack:true or ack:false)",                     "de": "Egal (ack:true oder ack:false)"},
    "tabOptions.triggerAckOptFalse": {               "en": "ack:false only (ignoriere ack:true)",             "de": "Nur ack:false (ignoriere ack:true)"},
    "tabOptions.triggerAckOptTrue": {                "en": "ack:true only (ignoriere ack:false)",             "de": "Nur ack:true (ignoriere ack:false)"},
    "tabOptions.triggerLimitHeader": {               "en": "Ignore trigger if last triggering of the same trigger was less than x seconds ago", "de": "Auslöser ignorieren, falls letzes Auslösen desselben Auslösers vor weniger als x Sekunden war"},
    "tabOptions.triggerLimitInfo": {                 "en": "For stability reasons, triggers are ignored if they were triggered less than x seconds ago. You can adjust this number of seconds here. Less than 1 second is not allowed.", "de": "Aus Stabilitätsgründen werden Auslöser ignoriert, wenn diese bereits vor weniger als x Sekunden ausgelöst haben. Du kannst diese Anzahl Sekunden hier anpassen. Weniger als 1 Sekunde ist nicht erlaubt."},
    "tabOptions.triggerLimitLabel": {                "en": "Minimum 1 second required",                       "de": "Mindestens 1 Sekunde erforderlich"},
};